### ISSUE TITLE
how to generate a spl2 file 

### ISSUE THREAD

**Issue by compileros** [s0sasaki/x86compiler#1]
hello dear Sasaki,
Firstly, thanks for your sharing.

I found in \old\compiler_minimal\readme.txt,
the command is the following: python compiler.py a.spl2 > a.s
but how to generate a spl2 file?
Thank your time and support.
Best regards,
Jason

**Comment by s0sasaki** [comment]
The a.spl2 file was written manually when I first wrote /old/compiler_minimal, which did not have a parser. After finishing the compiler_minimal, I wrote a parser (slr_parser.py in the main directory) to generate files like this. 
Hope this helps!
